database:
  filename: "database.db"

mine:
  ground:
    explosionPower: 2.5
    cosmetic: true
    adaptiveCosmetic: true
    breakBlocks: true
    fireBlocks: true

  hook:
    explosionPower: 1.0
    cosmetic: true
    breakBlocks: true
    fireBlocks: true